version: 0.1

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region eu-west-1)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t backend .
      - docker tag backend:latest 829851215903.dkr.ecr.eu-west-1.amazonaws.com/backend:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 829851215903.dkr.ecr.eu-west-1.amazonaws.com/backend:latest