version: 0.1

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region eu-west-1)
      - echo printing env
      - echo $(printenv)
      - echo printing code build env
      - echo $(CODEBUILD_BUILD_ID)
      - echo Generating custom Dockerrun file...
      - $(sed -i "" "s/<VERSION>/$CODEBUILD_BUILD_ID/g" Dockerrun.aws.json)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t backend .
      - docker tag backend:latest 829851215903.dkr.ecr.eu-west-1.amazonaws.com/backend:$(CODEBUILD_BUILD_ID)
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 829851215903.dkr.ecr.eu-west-1.amazonaws.com/backend:latest
artifacts:
  files:
    - Dockerrun.aws.json